databases:
  - name: HRMPortal
    plan: free
    databaseName: emsdb
    user: emsdb_owner

services:
  - type: web
    plan: free
    name: EMS
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn EMS.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: default
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
