databases:
  - name: emsdb
    plan: free
    databaseName: EMS
    user: EMS

services:
  - type: web
    plan: free
    name: EMS
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn EMS.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emsdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
